Disallow --command-fd
--command-fd appears safe, and indeed for a while it was thought to be
safe.  However, it turns out that GnuPG trusts the data it receives over
this file descriptor.  For instance, when not in batch mode, it will
prompt for a signed file if none is provided.  Also, it is trivial to
make GnuPG use a lot of CPU and memory, and it will eventually have a
(probably non-exploitable) integer overflow bug on really really long
input lines.

To avoid this problem, disallow --command-fd entirely.  It is used by
reprepro, so ignore it in the wrapper script.  Most of the operations
that require --command-fd, such as key generation and editing, are not
supported by split-gpg1 anyway.

diff --git a/gpg-client-wrapper b/gpg-client-wrapper
--- a/gpg-client-wrapper
+++ b/gpg-client-wrapper
@@ -85,6 +85,19 @@ while (( $# )); do
                 fi
                 shift 2
                 ;;
+            # --command-fd is used by reprepro, and looks safe.
+            # However, it turns out that GnuPG trusts the data it
+            # receives on this FD, so the backend has to reject it.
+            --command-fd=*)
+                shift
+                ;;
+            --command-fd)
+                if [[ "$#" -lt 2 ]]; then
+                    printf 'Missing argument to %s\n' "$1" >&2
+                    exit 1
+                fi
+                shift 2
+                ;;
             # Used by Mailpile, see https://github.com/QubesOS/qubes-issues/issues/3485
             --expert|--pinentry-mode=*|--passphrase-fd=*|--no-use-agent)
                 shift
